spring:
  h2:
    console:
      enabled: true
#      path: /h2-console

  # 프로필 설정
  profiles:
    active: local

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:h2:tcp://localhost/~/jlog
    username: sa
    password:


#  spring.datasource.driverClassName=
#  spring.datasource.url=jdbc:log4jdbc:mariadb://localhost:3306/test?characterEncoding=UTF-8&serverTimezone=UTC

  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: none

server:
  port: 3000

#  jpa:
#    defer-datasource-initialization: true

#  sql:
#    init:
#      mode: always

logging:
  config: classpath:log4j2.xml
  #  level:


jlog:
  jwt-key: "B9FcCRGDJjO8WAsE2eAcsT6cszyecPEps61+jVTahDg="