spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5

  datasource:
    url: jdbc:h2:tcp://localhost/~/jlog
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

server:
  port: 3000

#  jpa:
#    defer-datasource-initialization: true

#  sql:
#    init:
#      mode: always

jlog:
  jwt-key: "B9FcCRGDJjO8WAsE2eAcsT6cszyecPEps61+jVTahDg="